In [1]:
import pandas as pd

dfDnBMatchingLog = pd.read_csv('DnbDataAuthors/matchingRule/Attribute_importance_J48_2018-12-18_19-52-35-529_DnbDataAuthors.csv', sep=',', encoding='utf-8')

#dfDnBMatchingLog = dfDnBMatchingLog[dfDnBMatchingLog['Record2Identifier'].str.contains('viaf.org')]

display(dfDnBMatchingLog)

   Rank  Attribute  GainRatioImportance
0     1      label             1.299870
1     2        all             0.502449
2     3  deathdate             0.259688
3     4  birthdate             0.109170
4     5     gender             0.001147

In [2]:

uniqueValues = len(pd.unique(dfDnBMatchingLog[['0-RowComparatorLevenshtein-record1Value', '0-RowComparatorLevenshtein-record2Value']].values.ravel('K')))

In [3]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

dfSummary = pd.DataFrame()

dfDnBMatchingLogInfo = dfDnBMatchingLog.describe(include='all').transpose()

for index, row in dfDnBMatchingLogInfo.filter(like='postproccesedSimilarity', axis=0).iterrows():
    summary = {}
    dfDnBMatchingLogInfoSubset = dfDnBMatchingLogInfo.filter(like=index.replace('-postproccesedSimilarity', ''), axis=0)
    sRecord1Value = dfDnBMatchingLogInfoSubset.filter(like='-record1PreprocessedValue', axis=0).iloc[0]
    sRecord2Value = dfDnBMatchingLogInfoSubset.filter(like='-record2PreprocessedValue', axis=0).iloc[0]
        
    summary['density'] = (sRecord1Value['count'] + sRecord2Value['count']) /(2*len(dfDnBMatchingLog))
    summary['uniqueness'] = uniqueValues / (sRecord1Value['count'] + sRecord2Value['count'])
        
    summary['mean'] = row['mean']
    summary['std'] = row['std']
    summary['identifier'] = index.replace('-postproccesedSimilarity', '')
    summary['table'] = 'DnB'
        
    dfSummary = dfSummary.append(pd.DataFrame(summary, index=[0]))
    
display(dfSummary)

    density                             identifier      mean       std table  uniqueness
0  1.000000             0-RowComparatorLevenshtein  0.530731  0.365307   DnB    0.374233
0  1.000000                 1-RowComparatorJaccard  0.510671  0.390216   DnB    0.374233
0  1.000000          2-RowComparatorFirstCharacter  0.780368  0.414124   DnB    0.374233
0  1.000000              3-RowComparatorMongeElkan  0.219632  0.414124   DnB    0.374233
0  1.000000             4-RowComparatorJaroWinkler  0.947705  0.023438   DnB    0.374233
0  1.000000                5-RowComparatorNotEmpty  1.000000  0.000000   DnB    0.374233
0  0.919632         6-RowComparatorDateLevenshtein  0.694709  0.331082   DnB    0.406938
0  0.919632                7-RowComparatorDateYear  0.375460  0.484390   DnB    0.406938
0  0.919632           8-RowComparatorDateYearMonth  0.336196  0.472552   DnB    0.406938
0  0.919632                9-RowComparatorNotEmpty  0.844785  0.362220   DnB    0.406938
0  0.599693        10-RowComparatorDateLevenshtein  0.379256  0.430244   DnB    0.624041
0  0.599693               11-RowComparatorDateYear  0.238037  0.426012   DnB    0.624041
0  0.599693          12-RowComparatorDateYearMonth  0.222699  0.416186   DnB    0.624041
0  0.599693               13-RowComparatorNotEmpty  0.456442  0.498252   DnB    0.624041
0  0.984049         14-RowComparatorFirstCharacter  0.904908  0.293432   DnB    0.380299
0  0.984049                15-RowComparatorJaccard  0.904908  0.293432   DnB    0.380299
0  0.984049            16-RowComparatorLevenshtein  0.932993  0.216665   DnB    0.380299
0  0.984049             17-RowComparatorMongeElkan  0.063190  0.243379   DnB    0.380299
0  0.968098            18-RowComparatorJaroWinkler  0.740400  0.139419   DnB    0.386565
0  0.984049               19-RowComparatorNotEmpty  0.968098  0.175793   DnB    0.380299
0  1.000000  20-RowComparatorBagOfWordsContainment  0.178813  0.303171   DnB    0.374233
0  0.497546                21-RowComparatorJaccard  0.007512  0.039056   DnB    0.752158
0  0.497546               22-RowComparatorNotEmpty  0.246012  0.430818   DnB    0.752158

In [4]:
display(dfDnBMatchingLog['13-RowComparatorNotEmpty-record1Value'].value_counts(dropna=False))

NaN                 748
1903-01-01T00:00      8
1898-01-01T00:00      8
1703-09-29T00:00      7
1822-06-25T00:00      7
1943-11-26T00:00      6
1953-11-27T00:00      6
1945-02-25T00:00      5
1914-01-01T00:00      5
2008-03-23T00:00      5
1797-08-25T00:00      5
1968-09-21T00:00      5
2001-02-25T00:00      5
2012-01-29T00:00      4
1964-01-17T00:00      4
1654-12-05T00:00      4
1888-07-22T00:00      4
1974-01-09T00:00      4
1954-06-01T00:00      4
1607-01-01T00:00      4
2006-09-25T00:00      4
1987-08-16T00:00      4
1999-04-11T00:00      4
1881-08-13T00:00      4
1991-07-02T00:00      4
1998-05-29T00:00      4
1957-09-22T00:00      4
1995-04-11T00:00      3
2008-12-31T00:00      3
1929-06-10T00:00      3
1981-07-01T00:00      3
2009-06-23T00:00      3
1987-04-04T00:00      3
1977-10-27T00:00      3
1895-08-12T00:00      3
1987-08-17T00:00      3
1946-01-01T00:00      3
1982-09-19T00:00      3
1985-09-27T00:00      3
1727-10-26T00:00      3
1962-01-01T00:00      3
2016-07-27T00:00      3
2007-08-03T00:00      3
1886-01-01T00:00      2
2006-04-03T00:00      2
1928-10-23T00:00      2
1976-03-29T00:00      2
1993-09-08T00:00      2
1884-12-23T00:00      2
1845-12-19T00:00      2
1761-07-04T00:00      2
1920-03-23T00:00      2
1839-05-17T00:00      2
1848-07-04T00:00      2
1861-11-28T00:00      2
2012-10-01T00:00      2
1963-11-22T00:00      2
1915-03-24T00:00      2
1971-09-13T00:00      2
1792-06-10T00:00      2
2011-06-25T00:00      2
1998-11-16T00:00      2
1948-06-21T00:00      2
2002-11-07T00:00      2
1994-03-03T00:00      2
2012-03-16T00:00      2
1930-05-15T00:00      2
1914-03-31T00:00      2
1880-04-09T00:00      2
1964-04-26T00:00      2
1976-12-15T00:00      2
1972-01-01T00:00      2
1957-09-06T00:00      2
1915-10-25T00:00      2
1862-04-06T00:00      2
1928-05-18T00:00      2
1852-11-15T00:00      2
1964-01-01T00:00      2
2006-03-04T00:00      2
1936-05-23T00:00      2
1900-01-01T00:00      2
2013-03-17T00:00      2
2005-06-13T00:00      2
2011-01-04T00:00      2
2005-09-07T00:00      2
1948-06-07T00:00      2
1955-02-23T00:00      2
1947-02-17T00:00      2
1966-03-10T00:00      2
1854-01-01T00:00      2
1831-12-01T00:00      2
1933-01-01T00:00      2
2001-12-14T00:00      2
1976-01-08T00:00      2
2015-07-21T00:00      2
1943-10-24T00:00      2
1998-11-12T00:00      2
1948-11-23T00:00      2
1937-05-13T00:00      2
2011-12-12T00:00      2
1763-02-12T00:00      2
1970-10-07T00:00      2
1862-07-30T00:00      2
1927-10-13T00:00      2
1974-05-13T00:00      2
1974-06-02T00:00      2
1994-02-26T00:00      2
1985-03-07T00:00      2
1910-05-20T00:00      2
1980-01-01T00:00      2
1916-02-12T00:00      2
1926-03-28T00:00      2
1909-06-15T00:00      2
1936-11-23T00:00      2
1954-10-22T00:00      2
1709-09-04T00:00      2
2003-09-05T00:00      2
1970-07-15T00:00      2
1927-07-19T00:00      2
1993-09-24T00:00      2
1994-12-24T00:00      2
1989-04-19T00:00      2
1944-02-09T00:00      2
2004-10-04T00:00      2
2015-10-31T00:00      2
1984-04-16T00:00      2
2009-07-04T00:00      2
1961-09-02T00:00      2
1981-01-01T00:00      2
2010-01-22T00:00      2
1897-04-01T00:00      2
1988-01-01T00:00      2
2001-04-28T00:00      2
1932-09-26T00:00      2
1990-07-29T00:00      2
1970-01-01T00:00      2
1941-04-23T00:00      2
1961-12-24T00:00      2
1996-05-05T00:00      2
2005-07-16T00:00      2
1840-01-06T00:00      2
1867-05-23T00:00      2
2000-01-02T00:00      2
1995-05-21T00:00      2
1570-10-20T00:00      2
1999-06-12T00:00      2
1920-09-01T00:00      2
1965-08-31T00:00      2
2014-11-10T00:00      2
1975-09-20T00:00      2
1882-07-10T00:00      2
1878-11-30T00:00      2
1871-11-10T00:00      2
2010-01-13T00:00      2
1870-06-09T00:00      2
2004-09-28T00:00      2
1951-05-02T00:00      2
1800-01-01T00:00      2
2001-12-31T00:00      2
1954-04-08T00:00      2
1915-10-16T00:00      2
2011-06-02T00:00      2
1799-01-01T00:00      2
1907-02-11T00:00      2
2005-07-09T00:00      2
1879-12-30T00:00      2
1887-03-08T00:00      2
1996-07-27T00:00      2
1977-08-03T00:00      2
1933-05-23T00:00      2
1901-12-23T00:00      2
2009-02-09T00:00      2
1998-07-12T00:00      2
1656-08-01T00:00      2
1927-01-01T00:00      2
1837-02-13T00:00      2
1937-10-16T00:00      2
1723-05-11T00:00      2
1986-11-07T00:00      2
2003-10-18T00:00      2
1917-09-23T00:00      2
1961-06-02T00:00      2
1909-01-01T00:00      2
2013-04-30T00:00      2
1939-03-24T00:00      2
1937-05-24T00:00      2
1842-03-23T00:00      2
1999-11-28T00:00      2
2006-10-21T00:00      2
2003-02-13T00:00      2
1969-11-04T00:00      2
1997-10-16T00:00      2
1996-03-30T00:00      2
1905-02-02T00:00      2
1978-03-01T00:00      2
1903-08-11T00:00      2
1880-08-05T00:00      2
1920-06-17T00:00      2
1899-02-10T00:00      2
1918-07-16T00:00      2
1986-12-28T00:00      2
1882-05-04T00:00      2
1974-05-09T00:00      2
2001-06-06T00:00      2
1968-12-20T00:00      2
1825-11-14T00:00      2
2008-10-13T00:00      2
1965-01-04T00:00      2
1928-03-04T00:00      2
1992-01-01T00:00      2
2013-10-20T00:00      2
1950-06-25T00:00      2
1987-08-29T00:00      2
1678-01-16T00:00      2
1982-01-01T00:00      2
2008-04-02T00:00      2
2012-04-10T00:00      2
1966-04-01T00:00      2
1960-10-31T00:00      2
1951-11-09T00:00      2
1801-04-11T00:00      2
1977-10-10T00:00      2
2007-02-07T00:00      2
1954-08-03T00:00      2
1731-12-26T00:00      2
2012-05-23T00:00      2
1869-02-28T00:00      2
2015-09-20T00:00      2
1322-01-01T00:00      2
2009-02-23T00:00      2
1912-01-24T00:00      2
1999-08-23T00:00      2
1986-06-18T00:00      2
1916-03-12T00:00      2
2016-01-20T00:00      2
1993-07-23T00:00      2
1996-12-09T00:00      2
2010-01-21T00:00      2
1967-06-04T00:00      2
1994-04-28T00:00      2
1984-08-14T00:00      2
2002-10-27T00:00      2
1857-11-26T00:00      2
1992-06-22T00:00      2
1944-11-28T00:00      2
1968-06-16T00:00      2
1957-06-17T00:00      2
1944-05-09T00:00      2
1944-07-31T00:00      2
1893-09-29T00:00      2
1993-04-27T00:00      2
1994-04-09T00:00      2
1812-01-01T00:00      2
1938-01-01T00:00      2
1902-08-28T00:00      2
1985-08-12T00:00      2
1976-07-24T00:00      2
2008-07-04T00:00      2
2013-10-17T00:00      2
1836-10-27T00:00      2
2004-11-24T00:00      2
1819-03-23T00:00      2
1805-11-06T00:00      2
1993-01-01T00:00      2
1955-02-18T00:00      2
1946-08-13T00:00      2
1995-07-02T00:00      2
1952-02-19T00:00      2
1979-09-07T00:00      2
2011-11-04T00:00      2
1923-05-14T00:00      2
1991-02-07T00:00      2
1999-02-15T00:00      2
1893-08-05T00:00      2
2014-06-30T00:00      2
1930-06-13T00:00      2
1943-07-13T00:00      2
1900-01-20T00:00      2
2015-02-08T00:00      2
1668-01-01T00:00      2
1914-04-16T00:00      2
1826-11-26T00:00      2
1936-01-31T00:00      2
2001-12-03T00:00      2
1943-01-01T00:00      2
1900-08-16T00:00      2
1878-06-26T00:00      2
2005-06-11T00:00      2
1942-01-01T00:00      2
1966-10-22T00:00      2
1947-11-24T00:00      2
2011-12-13T00:00      2
1952-11-13T00:00      2
2015-03-03T00:00      2
1977-02-21T00:00      2
1701-06-02T00:00      2
1960-04-20T00:00      2
1980-11-21T00:00      2
1644-06-17T00:00      2
2014-04-26T00:00      2
1999-10-09T00:00      2
1998-12-01T00:00      2
1866-08-27T00:00      2
1865-01-01T00:00      2
1967-03-29T00:00      2
1821-08-24T00:00      2
2004-12-25T00:00      2
2000-01-26T00:00      2
1902-11-16T00:00      2
1987-09-20T00:00      2
1996-12-08T00:00      2
1896-10-08T00:00      2
1930-01-01T00:00      2
1999-12-12T00:00      2
1939-05-01T00:00      2
2007-01-01T00:00      2
1893-06-05T00:00      2
1916-11-13T00:00      2
2008-01-07T00:00      2
1918-12-23T00:00      2
2003-12-27T00:00      2
1937-03-09T00:00      2
1916-04-26T00:00      2
1684-01-01T00:00      2
1966-07-25T00:00      2
2006-02-02T00:00      2
1790-05-06T00:00      2
1952-07-12T00:00      2
1708-01-01T00:00      2
1896-06-20T00:00      2
1865-11-17T00:00      2
1881-07-09T00:00      2
1997-12-13T00:00      2
1846-06-13T00:00      2
1789-07-04T00:00      2
1996-08-25T00:00      2
1952-05-05T00:00      2
1949-02-01T00:00      2
1771-01-01T00:00      2
1986-01-07T00:00      2
1972-02-20T00:00      2
2002-09-13T00:00      2
1993-08-28T00:00      2
1986-05-13T00:00      2
1896-01-08T00:00      2
1693-05-25T00:00      2
1970-04-11T00:00      2
1882-05-11T00:00      2
2015-10-18T00:00      2
1881-04-24T00:00      2
1898-10-12T00:00      2
2001-12-28T00:00      2
1973-09-02T00:00      2
1988-06-22T00:00      2
1953-02-24T00:00      2
1920-01-02T00:00      2
1983-06-02T00:00      2
2000-11-10T00:00      2
1960-11-28T00:00      2
1829-03-12T00:00      2
1994-11-08T00:00      2
2012-11-02T00:00      2
1988-05-08T00:00      2
1946-03-20T00:00      2
1904-12-25T00:00      2
2005-01-01T00:00      2
1985-01-30T00:00      2
2013-04-19T00:00      2
1972-03-11T00:00      2
1971-07-11T00:00      2
1994-03-15T00:00      2
1695-04-13T00:00      2
1993-02-10T00:00      2
2010-01-18T00:00      2
2015-07-03T00:00      2
1875-01-01T00:00      2
1894-02-08T00:00      2
1936-01-16T00:00      2
1966-04-02T00:00      2
2009-04-19T00:00      2
1914-11-22T00:00      2
1990-10-20T00:00      2
1998-01-01T00:00      2
1978-09-24T00:00      2
1723-05-29T00:00      2
1952-11-18T00:00      2
1997-10-18T00:00      2
1936-10-19T00:00      2
1984-07-24T00:00      2
1659-06-03T00:00      2
1832-02-03T00:00      2
1902-04-20T00:00      2
2010-01-27T00:00      2
1956-06-22T00:00      2
1925-12-08T00:00      1
1947-06-06T00:00      1
2004-10-07T00:00      1
1981-09-07T00:00      1
Name: 13-RowComparatorNotEmpty-record1Value, dtype: int64

In [5]:
display(dfDnBMatchingLog['13-RowComparatorNotEmpty-record2Value'].value_counts(dropna=False))

NaN                 557
1904-07-16T00:00     83
1884-12-12T00:00     22
1859-04-14T00:00     12
1695-04-13T00:00      7
1723-05-29T00:00      6
1806-07-16T00:00      6
1970-01-01T00:00      5
1900-01-01T00:00      5
1852-05-12T00:00      4
1888-07-22T00:00      4
2012-03-16T00:00      4
1996-08-25T00:00      4
1846-06-13T00:00      4
1881-07-09T00:00      4
1943-11-26T00:00      4
2015-10-31T00:00      4
1944-07-31T00:00      4
1723-05-11T00:00      4
1914-01-01T00:00      4
1957-09-22T00:00      4
1865-04-22T00:00      4
1607-01-01T00:00      3
1709-09-04T00:00      3
1966-03-10T00:00      3
1903-08-11T00:00      3
1882-04-11T00:00      3
1962-01-01T00:00      3
1930-06-13T00:00      3
1845-12-19T00:00      3
1914-03-31T00:00      3
1884-12-23T00:00      3
1963-11-22T00:00      3
1925-12-08T00:00      3
1950-02-25T00:00      3
1977-01-01T00:00      3
1832-02-03T00:00      3
1980-01-01T00:00      3
1961-09-02T00:00      3
2006-06-18T00:00      3
1968-06-16T00:00      3
1893-09-29T00:00      3
2005-02-18T00:00      3
2015-07-03T00:00      3
1829-03-13T00:00      3
2017-04-24T00:00      3
1822-06-25T00:00      3
2005-06-13T00:00      3
2010-01-18T00:00      3
1930-01-01T00:00      3
1937-10-16T00:00      3
1970-04-11T00:00      3
2010-02-09T00:00      3
1974-01-19T00:00      3
1937-05-13T00:00      3
2004-04-23T00:00      3
1943-10-24T00:00      3
1668-01-01T00:00      3
2011-12-13T00:00      3
1928-05-28T00:00      3
1970-06-15T00:00      3
1999-10-09T00:00      3
1951-11-09T00:00      3
1965-08-31T00:00      3
1953-05-05T00:00      3
1963-11-04T00:00      3
2003-09-05T00:00      3
1993-07-27T00:00      3
1908-07-26T00:00      3
1928-05-18T00:00      3
1797-08-25T00:00      3
2008-07-04T00:00      3
1991-07-02T00:00      3
1837-02-13T00:00      3
1812-02-03T00:00      3
1984-01-17T00:00      2
1997-10-16T00:00      2
1939-05-01T00:00      2
1853-02-19T00:00      2
1893-06-05T00:00      2
2017-02-07T00:00      2
1957-01-01T00:00      2
1988-02-25T00:00      2
1916-04-26T00:00      2
2000-01-02T00:00      2
1977-10-18T00:00      2
2006-09-25T00:00      2
2008-04-18T00:00      2
1919-12-10T00:00      2
1860-06-09T00:00      2
1878-11-30T00:00      2
1920-06-17T00:00      2
1957-09-15T00:00      2
1886-01-01T00:00      2
1950-04-17T00:00      2
1827-05-12T00:00      2
1903-12-20T00:00      2
1654-12-05T00:00      2
1960-10-31T00:00      2
1972-12-26T00:00      2
1974-06-02T00:00      2
1929-06-10T00:00      2
1866-08-27T00:00      2
1927-11-03T00:00      2
1902-04-21T00:00      2
1951-05-02T00:00      2
1945-02-25T00:00      2
1916-11-13T00:00      2
1871-11-10T00:00      2
1954-04-08T00:00      2
1800-01-01T00:00      2
2012-05-15T00:00      2
1981-07-01T00:00      2
1684-01-01T00:00      2
1956-06-22T00:00      2
2008-03-23T00:00      2
1894-02-18T00:00      2
1958-03-24T00:00      2
1994-11-08T00:00      2
1917-09-23T00:00      2
1998-01-01T00:00      2
1990-10-20T00:00      2
1703-09-29T00:00      2
1662-03-28T00:00      2
1928-10-23T00:00      2
2010-01-27T00:00      2
1944-07-18T00:00      2
1998-11-12T00:00      2
2009-02-09T00:00      2
1987-09-20T00:00      2
1885-02-17T00:00      2
1973-09-02T00:00      2
1896-06-20T00:00      2
1960-07-27T00:00      2
1986-12-28T00:00      2
1999-02-15T00:00      2
1914-09-22T00:00      2
1763-02-12T00:00      2
2001-04-28T00:00      2
1998-05-29T00:00      2
2013-03-17T00:00      2
1936-01-16T00:00      2
1995-06-18T00:00      2
1742-11-09T00:00      2
1861-11-28T00:00      2
1843-03-11T00:00      2
2012-04-10T00:00      2
1997-11-04T00:00      2
2014-06-30T00:00      2
1880-08-05T00:00      2
1994-03-03T00:00      2
1999-04-11T00:00      2
1867-05-23T00:00      2
2011-01-04T00:00      2
2004-10-07T00:00      2
2002-11-07T00:00      2
1982-10-01T00:00      2
2004-11-29T00:00      2
1961-06-02T00:00      2
2006-03-04T00:00      2
1957-07-28T00:00      2
1986-05-13T00:00      2
1953-11-27T00:00      2
1991-02-07T00:00      2
1928-03-05T00:00      2
2003-02-13T00:00      2
1842-03-23T00:00      2
2000-01-26T00:00      2
1971-01-24T00:00      2
1878-06-29T00:00      2
1971-07-11T00:00      2
1960-11-28T00:00      2
1987-04-04T00:00      2
1948-11-23T00:00      2
1996-12-08T00:00      2
1882-03-08T00:00      2
1980-11-21T00:00      2
1996-03-30T00:00      2
2015-07-21T00:00      2
1854-01-01T00:00      2
1968-12-20T00:00      2
1916-02-12T00:00      2
1965-01-04T00:00      2
1644-06-17T00:00      2
1995-05-21T00:00      2
1910-05-20T00:00      2
1805-11-09T00:00      2
1984-04-16T00:00      2
1918-07-16T00:00      2
2017-04-07T00:00      2
1998-11-16T00:00      2
1994-12-24T00:00      2
1992-01-01T00:00      2
1954-10-22T00:00      2
1993-09-24T00:00      2
1934-09-14T00:00      2
1862-04-06T00:00      2
2013-10-20T00:00      2
1950-06-25T00:00      2
1936-11-23T00:00      2
1896-10-06T00:00      2
2017-01-02T00:00      2
1873-10-15T00:00      2
1678-01-16T00:00      2
2002-11-13T00:00      2
1967-03-29T00:00      2
1988-06-22T00:00      2
1869-02-28T00:00      2
1862-07-30T00:00      2
1999-08-23T00:00      2
1970-07-22T00:00      2
2009-02-23T00:00      2
1914-04-16T00:00      2
1898-01-01T00:00      2
1946-08-13T00:00      2
1993-08-28T00:00      2
1954-08-03T00:00      2
1852-11-15T00:00      2
2001-12-14T00:00      2
1927-11-21T00:00      2
1989-04-19T00:00      2
2007-08-03T00:00      2
2011-06-25T00:00      2
2012-10-01T00:00      2
1836-10-27T00:00      2
1794-07-23T00:00      2
2004-10-04T00:00      2
1987-08-17T00:00      2
1992-11-17T00:00      2
1998-07-16T00:00      2
1839-05-17T00:00      2
2005-09-07T00:00      2
1897-04-01T00:00      2
1580-06-10T00:00      2
1932-07-15T00:00      2
1994-04-28T00:00      2
1955-02-18T00:00      2
1949-02-01T00:00      2
1942-04-11T00:00      2
1995-07-02T00:00      2
1899-02-10T00:00      2
1980-07-02T00:00      2
1880-02-26T00:00      2
1994-05-02T00:00      2
1985-09-27T00:00      2
1924-08-07T00:00      2
2017-11-29T00:00      2
2005-10-12T00:00      2
1870-06-09T00:00      2
1972-07-30T00:00      2
                   ...
1967-08-03T00:00      1
1865-01-01T00:00      1
1825-11-14T00:00      1
1848-07-04T00:00      1
1940-10-14T00:00      1
1966-04-01T00:00      1
2001-06-06T00:00      1
1994-01-01T00:00      1
2003-06-23T00:00      1
1941-04-23T00:00      1
1934-06-07T00:00      1
1944-11-28T00:00      1
1708-01-01T00:00      1
1941-12-09T00:00      1
1976-01-01T00:00      1
2001-05-07T00:00      1
1953-01-01T00:00      1
1987-08-16T00:00      1
2008-10-13T00:00      1
1832-05-22T00:00      1
1879-12-30T00:00      1
1857-11-26T00:00      1
1945-04-10T00:00      1
1999-06-12T00:00      1
1947-03-15T00:00      1
1975-09-20T00:00      1
1835-11-07T00:00      1
1980-02-18T00:00      1
1915-10-25T00:00      1
1840-01-06T00:00      1
1966-04-22T00:00      1
2005-07-16T00:00      1
2001-07-28T00:00      1
1996-05-05T00:00      1
1979-02-28T00:00      1
1935-10-13T00:00      1
1986-11-07T00:00      1
2007-11-01T00:00      1
1982-01-01T00:00      1
1990-07-29T00:00      1
2008-04-02T00:00      1
1918-12-29T00:00      1
1792-07-10T00:00      1
1882-07-10T00:00      1
1972-08-20T00:00      1
1882-08-22T00:00      1
1894-02-08T00:00      1
1912-01-24T00:00      1
1936-05-23T00:00      1
1894-05-11T00:00      1
1968-09-21T00:00      1
2006-10-21T00:00      1
1607-11-27T00:00      1
1998-12-01T00:00      1
2002-05-06T00:00      1
2017-07-23T00:00      1
1937-05-24T00:00      1
2013-04-30T00:00      1
1779-02-24T00:00      1
1957-10-25T00:00      1
1881-08-13T00:00      1
1939-10-08T00:00      1
1955-02-23T00:00      1
1999-11-28T00:00      1
1981-08-15T00:00      1
2011-12-12T00:00      1
1926-10-06T00:00      1
1984-07-25T00:00      1
2003-10-18T00:00      1
1948-07-21T00:00      1
1946-03-20T00:00      1
1747-11-17T00:00      1
1985-01-30T00:00      1
1957-09-06T00:00      1
2013-04-19T00:00      1
1978-01-01T00:00      1
2013-01-01T00:00      1
2006-02-02T00:00      1
1946-01-01T00:00      1
1937-03-09T00:00      1
1936-10-19T00:00      1
1633-01-15T00:00      1
1831-01-21T00:00      1
1914-05-19T00:00      1
1942-11-22T00:00      1
1895-08-12T00:00      1
1790-05-06T00:00      1
1832-06-15T00:00      1
1952-07-12T00:00      1
1985-08-12T00:00      1
1928-04-30T00:00      1
2017-12-07T00:00      1
1924-03-19T00:00      1
1987-08-29T00:00      1
1938-01-01T00:00      1
1814-11-01T00:00      1
1974-05-13T00:00      1
2008-01-07T00:00      1
1975-10-09T00:00      1
1951-04-24T00:00      1
2010-08-17T00:00      1
1907-02-11T00:00      1
1881-04-24T00:00      1
1936-04-30T00:00      1
2016-07-27T00:00      1
1938-11-21T00:00      1
2009-05-07T00:00      1
1937-12-29T00:00      1
1903-01-22T00:00      1
1875-03-06T00:00      1
1943-03-05T00:00      1
1902-08-28T00:00      1
1881-01-13T00:00      1
1870-11-06T00:00      1
2004-11-24T00:00      1
1988-08-20T00:00      1
2013-10-17T00:00      1
1977-08-13T00:00      1
1570-10-21T00:00      1
2016-10-20T00:00      1
1858-12-18T00:00      1
1942-01-01T00:00      1
1322-01-01T00:00      1
1927-09-01T00:00      1
1899-07-11T00:00      1
1884-01-02T00:00      1
1905-02-02T00:00      1
1668-04-07T00:00      1
1976-07-23T00:00      1
2016-01-20T00:00      1
1993-01-07T00:00      1
1999-12-12T00:00      1
2012-11-02T00:00      1
1988-05-08T00:00      1
1972-03-11T00:00      1
1920-01-02T00:00      1
1904-12-25T00:00      1
2012-01-29T00:00      1
1982-04-23T00:00      1
1936-02-01T00:00      1
1944-06-29T00:00      1
1947-11-25T00:00      1
2009-04-19T00:00      1
1902-11-16T00:00      1
1960-04-21T00:00      1
2010-01-22T00:00      1
1870-01-01T00:00      1
1914-11-22T00:00      1
2018-05-24T00:00      1
1977-10-27T00:00      1
1930-04-28T00:00      1
1978-09-24T00:00      1
1981-09-07T00:00      1
1902-04-20T00:00      1
1952-11-18T00:00      1
1937-06-19T00:00      1
1909-02-20T00:00      1
1964-04-26T00:00      1
1984-08-14T00:00      1
1887-03-08T00:00      1
1659-06-03T00:00      1
1993-02-10T00:00      1
1971-01-01T00:00      1
1941-01-24T00:00      1
1977-08-15T00:00      1
1927-07-19T00:00      1
1961-01-01T00:00      1
1993-05-13T00:00      1
1821-08-24T00:00      1
1909-06-15T00:00      1
1727-10-26T00:00      1
2003-03-11T00:00      1
1966-04-02T00:00      1
1982-09-19T00:00      1
1731-12-26T00:00      1
2004-12-25T00:00      1
1988-05-12T00:00      1
1975-01-01T00:00      1
1962-11-18T00:00      1
1926-03-28T00:00      1
1974-10-28T00:00      1
1944-02-09T00:00      1
1952-11-13T00:00      1
1907-05-12T00:00      1
2003-12-27T00:00      1
1618-08-23T00:00      1
2012-05-23T00:00      1
1999-02-24T00:00      1
1761-07-04T00:00      1
1920-03-23T00:00      1
2009-06-23T00:00      1
2005-07-09T00:00      1
1923-05-14T00:00      1
1964-01-17T00:00      1
2011-11-04T00:00      1
2002-08-06T00:00      1
1979-09-07T00:00      1
1843-01-23T00:00      1
1952-02-19T00:00      1
1878-06-09T00:00      1
1971-09-13T00:00      1
1922-07-10T00:00      1
2003-03-06T00:00      1
1943-07-13T00:00      1
2017-06-13T00:00      1
2012-06-28T00:00      1
2009-07-04T00:00      1
1831-12-01T00:00      1
1993-09-08T00:00      1
1974-05-09T00:00      1
1985-03-07T00:00      1
1966-06-23T00:00      1
1789-07-04T00:00      1
1898-10-12T00:00      1
1933-05-23T00:00      1
2015-06-01T00:00      1
1994-04-09T00:00      1
1900-11-20T00:00      1
1946-02-03T00:00      1
1933-01-29T00:00      1
1986-01-07T00:00      1
1947-06-16T00:00      1
1993-04-28T00:00      1
2002-09-13T00:00      1
2015-09-20T00:00      1
1728-04-07T00:00      1
1896-01-08T00:00      1
1693-05-25T00:00      1
1986-06-18T00:00      1
1871-06-06T00:00      1
2008-12-31T00:00      1
1927-10-13T00:00      1
1933-01-01T00:00      1
1973-01-31T00:00      1
1976-01-08T00:00      1
1993-01-01T00:00      1
1928-02-07T00:00      1
2007-01-01T00:00      1
1938-11-04T00:00      1
1814-01-21T00:00      1
1967-06-04T00:00      1
2010-01-21T00:00      1
1996-12-09T00:00      1
1792-08-27T00:00      1
1913-01-01T00:00      1
1966-08-26T00:00      1
1775-02-16T00:00      1
1856-09-20T00:00      1
1916-03-12T00:00      1
1997-10-18T00:00      1
Name: 13-RowComparatorNotEmpty-record2Value, Length: 592, dtype: int64