In [1]:
import pandas as pd
import csv
import numpy as np

#Load Data
dfDBPedia = pd.read_csv('DBPediaAuthorsReduced.csv', sep=',')
dfDnb = pd.read_csv('DnbDataAuthorsReduced.csv', sep=',')
dfVIAF = pd.read_csv('VIAFDataAuthorsReduced.csv', sep=',')
dfWiki = pd.read_csv('WikiDataAuthorsReduced.csv', sep=',')

#Lowercase identifier
dfDBPedia['URI'] = dfDBPedia['URI'].str.lower()
dfDnb['uri'] = dfDnb['uri'].str.lower()
dfVIAF['uri'] = dfVIAF['uri'].str.lower()
dfWiki['uri'] = dfWiki['uri'].str.lower()

#Load True Matches
dfDnbGoldStandard = pd.read_csv('goldstandard_author_DnbDataAuthors.csv', sep=',', header=None)
dfVIAFGoldStandard = pd.read_csv('goldstandard_author_VIAFDataAuthors.csv', sep=',', header=None)
dfWikiGoldStandard = pd.read_csv('goldstandard_author_WikiDataAuthors.csv', sep=',', header=None)

In [2]:
display(dfDBPedia.describe())

,URI,abstract,birthdate,deathdate,gender,label,links,work
count,31604,31604,27313,14137,31604,31604,31604,7392
unique,31604,31604,18800,11439,7,31604,31604,7310
top,http://dbpedia.org/resource/helen_scales,Edward Pinnington (1846–1921) was a Scottish a...,1951-1-1,1993-1-1,male,Lorraine Bethel,\thttp://www.wikidata.org/entity/Q6370132\thtt...,\tMad_Men
freq,1,1,97,23,22377,1,1,13

In [3]:
dfDBPediaInfo = dfDBPedia.filter(items = ['birthdate', 'deathdate', 'gender', 'label', 'work']).describe()

datatypes = {'birthdate': ['date'], 'deathdate': ['date'], 
             'gender': ['string'], 'label': ['string'], 'work': ['list']}

dfDBPediaProfiling = pd.DataFrame(data= datatypes)
dfDBPediaProfiling = dfDBPediaProfiling.append((dfDBPediaInfo.loc[['count']] / len(dfDBPedia)).astype(np.float).round(3))
dfDBPediaProfiling = dfDBPediaProfiling.append((dfDBPediaInfo.loc[['unique']] / dfDBPediaInfo.loc[['count']].values).astype(np.float).round(3))

dfDBPediaProfiling.index = ['Data Type', 'Density', 'Uniqueness']

dfDBPediaProfiling.to_csv('DBPedia_author_profiling.csv', sep=',', encoding='utf-8', index=True, quotechar='"', quoting=csv.QUOTE_ALL)
#del dfDBPediaProfiling['Data Type']
display(dfDBPediaProfiling)
print(dfDBPediaProfiling.transpose().filter(items=['Density', 'Uniqueness']).to_latex())
dfDBPediaProfilingNew = dfDBPediaProfiling.transpose().filter(items=['Density', 'Uniqueness'])

           birthdate deathdate  gender   label   work
Data Type       date      date  string  string   list
Density        0.864     0.447       1       1  0.234
Uniqueness     0.688     0.809       0       1  0.989

\begin{tabular}{lll}
\toprule
{} & Density & Uniqueness \\
\midrule
birthdate &   0.864 &      0.688 \\
deathdate &   0.447 &      0.809 \\
gender    &       1 &          0 \\
label     &       1 &          1 \\
work      &   0.234 &      0.989 \\
\bottomrule
\end{tabular}

In [15]:
dfDnbInfo = dfDnb.filter(items = ['birthdate', 'deathdate', 'gender', 'label']).describe(include='all')

#display(dfDnbInfo)
datatypes = {'birthdate': ['date'], 'deathdate': ['date'], 'gender': ['string'], 'label': ['string']}

dfDnbProfiling = pd.DataFrame(data= datatypes)
display(dfDnb)
dfDnbProfiling = dfDnbProfiling.append((dfDnbInfo.loc[['count']] / len(dfDnb)).astype(np.float).round(3), sort = False)
dfDnbProfiling = dfDnbProfiling.append((dfDnbInfo.loc[['unique']] / dfDnbInfo.loc[['count']].values).astype(np.float).round(3), sort = False)

dfDnbProfiling.index = ['Data Type', 'Density', 'Uniqueness']

,uri,birthdate,deathdate,forename,gender,nameAddition,personalName,label,prefix,surname,work
0,http://d-nb.info/gnd/119047438,1936-01-01,1989-01-01,Abbie,notKnown,NaN,NaN,"Hoffman, Abbie",NaN,Hoffman,NaN
1,http://d-nb.info/gnd/119071606,1779-11-14,1850-01-20,Adam Gottlob,male,NaN,NaN,"Oehlenschläger, Adam Gottlob",NaN,Oehlenschläger,NaN
2,http://d-nb.info/gnd/1028840020,1937-01-01,1995-08-23,Adam,notKnown,NaN,NaN,"Wiśniewski-Snerg, Adam",NaN,Wiśniewski-Snerg,NaN
3,http://d-nb.info/gnd/118744895,1929-05-16,2012-03-27,Adrienne,female,NaN,NaN,"Rich, Adrienne",NaN,Rich,NaN
4,http://d-nb.info/gnd/118577409,1785-03-07,1873-05-22,Alessandro,male,NaN,NaN,"Manzoni, Alessandro",NaN,Manzoni,NaN
5,http://d-nb.info/gnd/118658654,1913-01-01,1987-01-01,Alfred,notKnown,NaN,NaN,"Bester, Alfred",NaN,Bester,NaN
6,http://d-nb.info/gnd/118884433,1944-02-09,NaN,Alice,female,NaN,NaN,"Walker, Alice",NaN,Walker,NaN
7,http://d-nb.info/gnd/119363925,1952-01-01,NaN,Amy,female,NaN,NaN,"Tan, Amy",NaN,Tan,NaN
8,http://d-nb.info/gnd/118578448,1621-01-01,1678-01-01,Andrew,notKnown,NaN,NaN,"Marvell, Andrew",NaN,Marvell,NaN
9,http://d-nb.info/gnd/122951786,1928-01-01,2012-01-01,Andrew,notKnown,NaN,NaN,"Sarris, Andrew",NaN,Sarris,NaN
10,http://d-nb.info/gnd/118515187,1896-02-18,1966-09-28,André,male,NaN,NaN,"Breton, André",NaN,Breton,NaN
11,http://d-nb.info/gnd/118576844,1901-01-01,1976-01-01,André,male,NaN,NaN,"Malraux, André",NaN,Malraux,NaN
12,http://d-nb.info/gnd/118598732,1907-01-01,1998-01-01,Dominique,notKnown,NaN,NaN,"Aury, Dominique",NaN,Aury,NaN
13,http://d-nb.info/gnd/118638092,1917-02-25,1993-11-25,Anthony,male,NaN,NaN,"Burgess, Anthony",NaN,Burgess,NaN
14,http://d-nb.info/gnd/118781057,1863-03-03,1947-12-15,Arthur,male,NaN,NaN,"Machen, Arthur",NaN,Machen,NaN
15,http://d-nb.info/gnd/118573217,1907-11-14,2002-01-28,Astrid,female,NaN,NaN,"Lindgren, Astrid",NaN,Lindgren,NaN
16,http://d-nb.info/gnd/118619314,1849-01-22,1912-05-14,August,male,NaN,NaN,"Strindberg, August",NaN,Strindberg,NaN
17,http://d-nb.info/gnd/118512145,1931-01-01,2009-01-01,Augusto,notKnown,NaN,NaN,"Boal, Augusto",NaN,Boal,NaN
18,http://d-nb.info/gnd/118558323,1572-06-11,1637-08-06,Ben,male,NaN,NaN,"Jonson, Ben",NaN,Jonson,NaN
19,http://d-nb.info/gnd/118794353,1878-01-06,1967-07-22,Carl,male,NaN,NaN,"Sandburg, Carl",NaN,Sandburg,NaN
20,http://d-nb.info/gnd/130457671,1924-11-21,NaN,Christopher,notKnown,NaN,NaN,"Tolkien, Christopher",NaN,Tolkien,NaN
21,http://d-nb.info/gnd/119420139,1340-01-01,1370-01-01,NaN,notKnown,Ap Gwilym,Dafydd,"Dafydd, Ap Gwilym",NaN,NaN,NaN
22,http://d-nb.info/gnd/107522535,1922-09-19,2002-04-15,Damon,male,NaN,NaN,"Knight, Damon",NaN,Knight,NaN
23,http://d-nb.info/gnd/129035998,1931-07-07,2009-06-02,David,male,NaN,NaN,"Eddings, David",NaN,Eddings,NaN
24,http://d-nb.info/gnd/122865251,1962-02-21,2008-09-12,David Foster,male,NaN,NaN,"Wallace, David Foster",NaN,Wallace,NaN
25,http://d-nb.info/gnd/118776355,1895-11-01,1974-10-28,David Michael,male,NaN,NaN,"Jones, David Michael",NaN,Jones,NaN
26,http://d-nb.info/gnd/124918034,1952-01-01,NaN,David,notKnown,NaN,NaN,"Zindell, David",NaN,Zindell,NaN
27,http://d-nb.info/gnd/123453658,1934-08-16,2011-03-26,Diana Wynne,notKnown,NaN,NaN,"Jones, Diana Wynne",NaN,Jones,NaN
28,http://d-nb.info/gnd/124788297,1904-01-01,1977-01-01,Edmond,notKnown,NaN,NaN,"Hamilton, Edmond",NaN,Hamilton,NaN
29,http://d-nb.info/gnd/118512102,1896-01-01,1974-01-01,Edmund,notKnown,NaN,NaN,"Blunden, Edmund",NaN,Blunden,NaN
...,...,...,...,...,...,...,...,...,...,...,...
9968,http://d-nb.info/gnd/1067579257,1948-01-01,NaN,Paul,male,NaN,NaN,"Kivel, Paul",NaN,Kivel,NaN
9969,http://d-nb.info/gnd/1017966303,1943-01-01,NaN,David,notKnown,NaN,NaN,"Rosenberg, David",NaN,Rosenberg,NaN
9970,http://d-nb.info/gnd/124793975,1961-01-01,NaN,Greg,notKnown,NaN,NaN,"Kennedy, Greg",NaN,Kennedy,NaN
9971,http://d-nb.info/gnd/128893842,1969-01-01,NaN,Leora,notKnown,NaN,NaN,"Tanenbaum, Leora",NaN,Tanenbaum,NaN
9972,http://d-nb.info/gnd/119478811,1165-01-01,1230-01-01,NaN,notKnown,de Beaujeu,Renaut,"Renaut, de Beaujeu",NaN,NaN,NaN
9973,http://d-nb.info/gnd/1079820051,1957-01-01,NaN,Steve,male,NaN,NaN,"Silberman, Steve",NaN,Silberman,NaN
9974,http://d-nb.info/gnd/120561395,1952-11-24,NaN,Merry E.,female,NaN,NaN,"Wiesner, Merry E.",NaN,Wiesner,NaN
9975,http://d-nb.info/gnd/137021615,1969-01-01,NaN,William,notKnown,NaN,NaN,"Egginton, William",NaN,Egginton,NaN
9976,http://d-nb.info/gnd/13370632x,1975-01-01,NaN,Yasmina,notKnown,NaN,NaN,"Traboulsi, Yasmina",NaN,Traboulsi,NaN
9977,http://d-nb.info/gnd/140741925,1965-01-01,2017-01-01,Amy Krouse,female,NaN,NaN,"Rosenthal, Amy Krouse",NaN,Rosenthal,NaN
9978,http://d-nb.info/gnd/102418586,NaN,1408-01-01,NaN,notKnown,Coloniensis,Adamus,"Adamus, Coloniensis",NaN,NaN,NaN
9979,http://d-nb.info/gnd/118712187,NaN,NaN,NaN,notKnown,Bălgarski,Joan,"Joan, Bălgarski",NaN,NaN,NaN
9980,http://d-nb.info/gnd/1016908792,1961-01-01,NaN,Michael,notKnown,NaN,NaN,"Helm, Michael",NaN,Helm,NaN
9981,http://d-nb.info/gnd/129517186,1955-09-24,NaN,Gail,female,NaN,NaN,"Giles, Gail",NaN,Giles,NaN
9982,http://d-nb.info/gnd/138985863,NaN,NaN,Stephen F.,notKnown,NaN,NaN,"Jones, Stephen F.",NaN,Jones,NaN
9983,http://d-nb.info/gnd/140993312,NaN,NaN,Scott,NaN,NaN,NaN,"Moore, Scott",NaN,Moore,NaN
9984,http://d-nb.info/gnd/138117284,1962-01-01,NaN,Nikki,notKnown,NaN,NaN,"Tate, Nikki",NaN,Tate,NaN
9985,http://d-nb.info/gnd/142079219,NaN,NaN,Nicola,notKnown,NaN,NaN,"Cornick, Nicola",NaN,Cornick,NaN
9986,http://d-nb.info/gnd/128698802,1949-01-01,NaN,Roy Bin,male,NaN,NaN,"Wong, Roy Bin",NaN,Wong,NaN
9987,http://d-nb.info/gnd/1059431351,NaN,NaN,Jason,notKnown,NaN,NaN,"Healey, Jason",NaN,Healey,NaN
9988,http://d-nb.info/gnd/104277777,NaN,NaN,NaN,notKnown,di Tura,Agnolo,"Agnolo, di Tura",NaN,NaN,NaN
9989,http://d-nb.info/gnd/1056130431,NaN,NaN,NaN,notKnown,NaN,Dafydd Bach ap Madog Wladaidd,Dafydd Bach ap Madog Wladaidd,NaN,NaN,NaN
9990,http://d-nb.info/gnd/134070356,NaN,NaN,F. E.,notKnown,NaN,NaN,"Higgins, F. E.",NaN,Higgins,NaN
9991,http://d-nb.info/gnd/139045228,NaN,NaN,Andrew,notKnown,NaN,NaN,"Lycett, Andrew",NaN,Lycett,NaN
9992,http://d-nb.info/gnd/12891887x,NaN,NaN,NaN,notKnown,NaN,Ngô-sĩ-Liên,Ngô-sĩ-Liên,NaN,NaN,NaN
9993,http://d-nb.info/gnd/138506884,1979-01-01,NaN,Sana,female,NaN,NaN,"Krasikov, Sana",NaN,Krasikov,NaN
9994,http://d-nb.info/gnd/142450936,NaN,NaN,John,notKnown,NaN,NaN,"Vaillant, John",NaN,Vaillant,NaN
9995,http://d-nb.info/gnd/1025290070,NaN,NaN,Gina M.,notKnown,NaN,NaN,"Biegel, Gina M.",NaN,Biegel,NaN
9996,http://d-nb.info/gnd/14328178x,NaN,NaN,Margi,female,NaN,NaN,"Preus, Margi",NaN,Preus,NaN
9997,http://d-nb.info/gnd/137139349,1967-01-01,NaN,Saci,notKnown,NaN,NaN,"Lloyd, Saci",NaN,Lloyd,NaN

In [16]:
from nltk import word_tokenize, ngrams
from nltk.metrics import jaccard_distance
import numpy as np

mapping = {"birthdate": "birthdate", "deathdate": "deathdate", "gender": "gender", "label": "label", "work": "work"}
jaccard_similarity_counter = {"birthdate" : 0, "deathdate": 0, "gender":0, "label": 0, "work": 0}

for index, row in dfDnbGoldStandard.iterrows():
    rowDBPedia = dfDBPedia[dfDBPedia['URI'] == row[0]]
    rowDnb = dfDnb[dfDnb['uri'] == row[1]]
    for key in mapping:
        if type(rowDnb[key].values[0]) not in[np.float64, float] and type(rowDBPedia[mapping[key]].values[0]) not in[np.float64, float]:
            jaccard_similarity_counter[key] += jaccard_distance(set(ngrams(rowDBPedia[mapping[key]].values[0], 2)), set(ngrams(rowDnb[key].values[0], 2)))
    
for key in jaccard_similarity_counter:
    jaccard_similarity_counter[key] = round(jaccard_similarity_counter[key] / len(dfDnbGoldStandard), 3)
 
#display(jaccard_similarity_counter)
dfDnbProfiling = dfDnbProfiling.append(pd.DataFrame(data=jaccard_similarity_counter, index=['Heterogeneity']))
#dfDnbProfiling.to_csv('Dnb_author_profiling.csv', sep=',', encoding='utf-8', index=True, quotechar='"', quoting=csv.QUOTE_ALL)
print(dfDnbProfiling.transpose().filter(items=['Density', 'Uniqueness', 'Heterogeneity']).to_latex())

\begin{tabular}{llll}
\toprule
{} & Density & Uniqueness & Heterogeneity \\
\midrule
birthdate &   0.945 &      0.417 &         0.326 \\
deathdate &   0.577 &      0.534 &         0.177 \\
gender    &   0.986 &          0 &         0.413 \\
label     &       1 &      0.997 &           0.4 \\
work      &     NaN &        NaN &             0 \\
\bottomrule
\end{tabular}

C:\Users\Alex\Anaconda3\envs\py36\lib\site-packages\pandas\core\frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

In [24]:
display(dfDnbProfiling)

              birthdate deathdate  gender   label  work
Data Type          date      date  string  string   NaN
Density           0.945     0.577   0.986       1   NaN
Uniqueness        0.417     0.534       0   0.997   NaN
Heterogeneity     0.326     0.177   0.413     0.4   0.0

In [17]:
dfVIAFInfo = dfVIAF.filter(items = ['birthdate', 'deathdate', 'gender', 'label', 'work']).describe(include='all')
datatypes = {'birthdate': ['date'], 'deathdate': ['date'], 'gender': ['string'], 'label': ['string'], 'work': ['string']}

dfVIAFProfiling = pd.DataFrame(data= datatypes)
dfVIAFProfiling = dfVIAFProfiling.append((dfVIAFInfo.loc[['count']] / len(dfVIAF)).astype(np.float).round(3), sort = False)
dfVIAFProfiling = dfVIAFProfiling.append((dfVIAFInfo.loc[['unique']] / dfVIAFInfo.loc[['count']].values).astype(np.float).round(3), sort = False)

dfVIAFProfiling.index = ['Data Type', 'Density', 'Uniqueness']

In [18]:
from nltk import word_tokenize, ngrams
from nltk.metrics import jaccard_distance
import numpy as np

mapping = {"birthdate": "birthdate", "deathdate": "deathdate", "gender": "gender", "label": "label", "work": "work"}
jaccard_similarity_counter = {"birthdate" : 0, "deathdate": 0, "gender":0, "label": 0, "work": 0}

for index, row in dfVIAFGoldStandard.iterrows():
    rowDBPedia = dfDBPedia[dfDBPedia['URI'] == row[0]]
    rowVIAF = dfVIAF[dfVIAF['uri'] == row[1]]
    for key in mapping:
        if type(rowVIAF[key].values[0]) not in[np.float64, float] and type(rowDBPedia[mapping[key]].values[0]) not in[np.float64, float]:
            jaccard_similarity_counter[key] += jaccard_distance(set(ngrams(rowDBPedia[mapping[key]].values[0], 2)), set(ngrams(rowVIAF[key].values[0], 2)))
    
for key in jaccard_similarity_counter:
    jaccard_similarity_counter[key] = round(jaccard_similarity_counter[key] / len(dfVIAFGoldStandard),3)
 
#display(jaccard_similarity_counter)
dfVIAFProfiling = dfVIAFProfiling.append(pd.DataFrame(data=jaccard_similarity_counter, index=['Heterogeneity']))
dfVIAFProfiling.to_csv('viaf_author_profiling.csv', sep=',', encoding='utf-8', index=False, quotechar='"', quoting=csv.QUOTE_ALL)

print(dfVIAFProfiling.transpose().filter(items=['Density', 'Uniqueness', 'Heterogeneity']).to_latex())

\begin{tabular}{llll}
\toprule
{} & Density & Uniqueness & Heterogeneity \\
\midrule
birthdate &    0.99 &      0.828 &         0.166 \\
deathdate &   0.597 &      0.911 &         0.077 \\
gender    &   0.977 &          0 &             0 \\
label     &   0.999 &      0.997 &         0.143 \\
work      &   0.757 &      0.983 &         0.245 \\
\bottomrule
\end{tabular}

In [19]:
dfWikiInfo = dfWiki.filter(items = ['birthdate', 'deathdate', 'gender', 'label', 'work']).describe(include='all')
datatypes = {'birthdate': ['date'], 'deathdate': ['date'], 'gender': ['string'], 'label': ['string'], 'work': ['string']}

dfWikiProfiling = pd.DataFrame(data= datatypes)
dfWikiProfiling = dfWikiProfiling.append((dfWikiInfo.loc[['count']] / len(dfWiki)).astype(np.float).round(3), sort = False)
dfWikiProfiling = dfWikiProfiling.append((dfWikiInfo.loc[['unique']] / dfWikiInfo.loc[['count']].values).astype(np.float).round(3), sort = False)

dfWikiProfiling.index = ['Data Type', 'Density', 'Uniqueness']

In [20]:
from nltk import word_tokenize, ngrams
from nltk.metrics import jaccard_distance
import numpy as np

mapping = {"birthdate": "birthdate", "deathdate": "deathdate", "gender": "gender", "label": "label", "work": "work"}
jaccard_similarity_counter = {"birthdate" : 0, "deathdate": 0, "gender":0, "label": 0, "work": 0}

for index, row in dfWikiGoldStandard.iterrows():
    rowDBPedia = dfDBPedia[dfDBPedia['URI'] == row[0]]
    rowWiki = dfWiki[dfWiki['uri'] == row[1]]
    for key in mapping:
        if type(rowWiki[key].values[0]) not in[np.float64, float] and type(rowDBPedia[mapping[key]].values[0]) not in[np.float64, float]:
            jaccard_similarity_counter[key] += jaccard_distance(set(ngrams(rowDBPedia[mapping[key]].values[0], 2)), set(ngrams(rowWiki[key].values[0], 2)))
    
for key in jaccard_similarity_counter:
    jaccard_similarity_counter[key] = round(jaccard_similarity_counter[key] / len(dfWikiGoldStandard),3)
 
#display(jaccard_similarity_counter)
dfWikiProfiling = dfWikiProfiling.append(pd.DataFrame(data=jaccard_similarity_counter, index=['Heterogeneity']))
dfWikiProfiling.to_csv('wiki_author_profiling.csv', sep=',', encoding='utf-8', index=True, quotechar='"', quoting=csv.QUOTE_ALL)

print(dfWikiProfiling.transpose().filter(items=['Density', 'Uniqueness', 'Heterogeneity']).to_latex())

\begin{tabular}{llll}
\toprule
{} & Density & Uniqueness & Heterogeneity \\
\midrule
birthdate &   0.918 &      0.627 &         0.462 \\
deathdate &   0.466 &      0.778 &         0.232 \\
gender    &       1 &          0 &         0.001 \\
label     &       1 &      0.996 &         0.051 \\
work      &   0.082 &      0.988 &         0.046 \\
\bottomrule
\end{tabular}

In [21]:
print(dfWikiProfiling.to_latex(bold_rows=True, multicolumn=True))

\begin{tabular}{llllll}
\toprule
{} & birthdate & deathdate &  gender &   label &    work \\
\midrule
\textbf{Data Type    } &      date &      date &  string &  string &  string \\
\textbf{Density      } &     0.918 &     0.466 &       1 &       1 &   0.082 \\
\textbf{Uniqueness   } &     0.627 &     0.778 &       0 &   0.996 &   0.988 \\
\textbf{Heterogeneity} &     0.462 &     0.232 &   0.001 &   0.051 &   0.046 \\
\bottomrule
\end{tabular}

In [22]:
dfDBPediaProfiling.to_csv('DBPedia_author_profiling.csv', sep=',', encoding='utf-8', index=True, quotechar='"', quoting=csv.QUOTE_ALL)
dfVIAFProfiling.to_csv('viaf_author_profiling.csv', sep=',', encoding='utf-8', index=True, quotechar='"', quoting=csv.QUOTE_ALL)
dfWikiProfiling.to_csv('wiki_author_profiling.csv', sep=',', encoding='utf-8', index=True, quotechar='"', quoting=csv.QUOTE_ALL)
dfDnbProfiling.to_csv('Dnb_author_profiling.csv', sep=',', encoding='utf-8', index=True, quotechar='"', quoting=csv.QUOTE_ALL)

In [23]:
dfAggregatedProfiling = dfDBPediaProfiling.transpose().append(dfVIAFProfiling.transpose())
dfAggregatedProfiling = dfAggregatedProfiling.append(dfWikiProfiling.transpose())
dfAggregatedProfiling = dfAggregatedProfiling.append(dfDnbProfiling.transpose())

dfSummedProfiling = pd.DataFrame()
for index in set(dfAggregatedProfiling.index):
    profil = {}
    dfSubset = dfAggregatedProfiling.loc[index]
    profil['Attribute'] = index
    profil['Density-Mean'] = dfSubset['Density'].mean()
    profil['Density-Std'] = dfSubset['Density'].std()
    profil['Heterogeneity-Mean'] = dfSubset['Heterogeneity'].mean()
    profil['Heterogeneity-Std'] = dfSubset['Heterogeneity'].std()
    profil['Uniqueness-Mean'] = dfSubset['Uniqueness'].mean()
    profil['Uniqueness-Std'] = dfSubset['Uniqueness'].std()
    dfProfil = pd.DataFrame(profil, index=[0])
    dfSummedProfiling = dfSummedProfiling.append(dfProfil)

display(dfSummedProfiling)
dfSummedProfiling.to_csv('author_profiling.csv', sep=',', encoding='utf-8', index=True, quotechar='"', quoting=csv.QUOTE_ALL)

C:\Users\Alex\Anaconda3\envs\py36\lib\site-packages\pandas\core\frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

,Attribute,Density-Mean,Density-Std,Heterogeneity-Mean,Heterogeneity-Std,Uniqueness-Mean,Uniqueness-Std
0,label,0.999750,0.000500,0.198,0.180884,0.997500,0.001732
0,deathdate,0.521750,0.076181,0.162,0.078581,0.758000,0.159777
0,gender,0.990750,0.011295,0.138,0.238158,0.000000,0.000000
0,birthdate,0.929250,0.052671,0.318,0.148162,0.640000,0.170827
0,work,0.357667,0.354085,0.097,0.130219,0.986667,0.003215